<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>my.quarker</groupId>
  <artifactId>quarker-teavm-build</artifactId>
  <version>1.0.0</version>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <teavm.version>0.14.0</teavm.version>
    <quarker.web.classFiles>${project.basedir}/../../build/classes-web</quarker.web.classFiles>
    <quarker.web.targetDirectory>${project.basedir}/../../build/web/teavm-out/assets</quarker.web.targetDirectory>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-core</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-platform</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso-apis</artifactId>
      <version>${teavm.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.teavm</groupId>
        <artifactId>teavm-maven-plugin</artifactId>
        <version>${teavm.version}</version>
        <configuration>
          <mainClass>my.quarker.QuarkerWeb</mainClass>
          <targetType>JAVASCRIPT</targetType>
          <jsModuleType>NONE</jsModuleType>
          <targetFileName>quarker.js</targetFileName>
          <targetDirectory>${quarker.web.targetDirectory}</targetDirectory>
          <classFiles>${quarker.web.classFiles}</classFiles>
          <minifying>false</minifying>
          <sourceMapsGenerated>false</sourceMapsGenerated>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
